logging:
  level:
    .: error
    org.springframework: ERROR
    com.mkyong: ERROR

spring:
  profiles:
    active: "dev"
  main:
    banner-mode: "off"

server:
  email: default@mkyong.com

---

spring:
  profiles: dev
server:
  mongoURI: mongodb://10.8.0.23:27017
  mongoDB: test
  farmDB: farmTest
  cropDB: cropTest
  deviceDB: deviceTest

---

spring:
  profiles: prod
server:
  mongoURI: mongodb://10.8.0.23:27017
  mongoDB: production
  farmDB: Farm
  cropDB: Crops
  deviceDB: Devices